// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Populate_EntityMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Populate_EntityMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "201708232149288_Populate_EntityMovie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
